name: Firefox Android
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/firefox_android.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/android_l10n.py'
      - 'l10n/exceptions/firefox_android.json'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/firefox_android.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/android_l10n.py'
      - 'l10n/exceptions/firefox_android.json'
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 9 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    with:
      repository: mozilla-l10n/android-l10n
      script: android_l10n.py
      script_args: >-
        --toml target_repo/firefox.toml
        --dest errors.txt
        --exceptions scripts_repo/l10n/exceptions/firefox_android.json
        --no-failure
