name: Focus iOS
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/focus_ios.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/xliff_l10n.py'
      - 'l10n/exceptions/focus_ios.json'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/focus_ios.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/xliff_l10n.py'
      - 'l10n/exceptions/focus_ios.json'
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 9 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    with:
      repository: mozilla-l10n/focusios-l10n
      script: xliff_l10n.py
      script_args: >-
        --l10n target_repo/
        --dest errors.txt
        --exceptions scripts_repo/l10n/exceptions/focus_ios.json
        --no-failure
