name: FxA CMS
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/fxa_cms.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/fxa_cms.json'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/fxa_cms.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/fxa_cms.json'
  schedule:
    - cron: '10 1 * * *'
    - cron: '10 9 * * *'
    - cron: '10 17 * * *'
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    with:
      repository: mozilla/fxa-cms-l10n
      script: fluent_l10n.py
      script_args: >-
        --l10n target_repo/locales/
        --ref en
        --dest errors.txt
        --exceptions scripts_repo/l10n/exceptions/fxa_cms.json
        --no-failure
