name: FxA Gettext
on:
  schedule:
    - cron: '10 1,13 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          path: "scripts_repo"
      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla/fxa-content-server-l10n"
          path: "target_repo"
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          pip install -r scripts_repo/.github/requirements.txt
      - name: Lint localization
        # Allow to continue if the linter fails, so we can upload the list of
        # errors as artifact
        continue-on-error: true
        run: |
          python scripts_repo/l10n/gettext_l10n.py --l10n target_repo/locale/ --dest errors.txt --exceptions scripts_repo/l10n/exceptions/fxa_gettext.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: errors-list
          path: errors.txt
          if-no-files-found: ignore
      - name: Fail on errors
        run: |
          if [ -f "errors.txt" ]; then
            cat errors.txt
            exit 1
          fi
