name: MozOrg
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/mozorg.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/mozorg.json'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/mozorg.yaml'
      - '.github/workflows/_lint.yaml'
      - '.github/requirements.txt'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/mozorg.json'
  schedule:
    - cron: '10 1 * * *'
    - cron: '10 9 * * *'
    - cron: '10 17 * * *'
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    with:
      repository: mozilla-l10n/www-l10n
      script: fluent_l10n.py
      script_args: >-
        --toml target_repo/l10n-vendor.toml
        --ref en
        --dest errors_vendors.txt
        --exceptions scripts_repo/l10n/exceptions/mozorg.json
        --no-failure
      script_args_2: >-
        --toml target_repo/l10n-pontoon.toml
        --ref en
        --dest errors_community.txt
        --exceptions scripts_repo/l10n/exceptions/mozorg.json
        --no-failure
